CELL_TYPE_MARKERS = {
    "cancer": [
        "PHOX2B",
        "TH",
        "CHGA",
        "CHGB",
        "ENO2",
        "GAP43",
        "ISL1",
        "MYCN",
    ],
    "cytotoxic_t": [
        "CD3D",
        "CD3E",
        "TRAC",
        "CD8A",
        "CD8B",
        "NKG7",
        "CST7",
        "PRF1",
        "GZMB",
        "IFNG",
        "CCL5",
    ],
    "monocyte": [
        "LYZ",
        "FCN1",
        "S100A8",
        "S100A9",
        "CTSS",
        "TYMP",
        "SAT1",
        "VCAN",
        "CCR2",
    ],
    "macrophage": [
        "CD68",
        "APOE",
        "C1QA",
        "C1QB",
        "C1QC",
        "MSR1",
        "MRC1",
        "LILRB1",
        "SPP1",
    ],
}

PROGRAM_MARKERS = {
    "tumor_growth": ["MKI67", "TOP2A", "PCNA", "CCNB1", "CDK1"],
    "tumor_stress": ["BAX", "BBC3", "PMAIP1", "FAS", "CASP3"],
    "tcell_cytotoxicity": ["NKG7", "PRF1", "GZMB", "GNLY", "IFNG", "CCL5"],
    "tcell_exhaustion": ["PDCD1", "LAG3", "HAVCR2", "TIGIT", "TOX"],
    "monocyte_recruitment": ["CCR2", "S100A8", "S100A9", "FCN1", "CTSB", "TYMP"],
    "monocyte_antigen_presentation": [
        "B2M",
        "HLA-A",
        "HLA-B",
        "HLA-C",
        "TAP1",
        "TAPBP",
    ],
    "macrophage_polarization": ["CD68", "APOE", "C1QC", "MRC1", "IL10", "TGFB1"],
    "macrophage_inflammation": ["IL1B", "TNF", "CXCL8", "NFKBIA", "CCL2"],
}

